auth_token = "FU$Ic-!_v^YQuEqW"
bind_address = "0.0.0.0:12345"
video_name = "{{title}}"
page_name = "{{title}}"
multi_page_name = "{{title}}-P{{pid_pad}}"
bangumi_name = "第{{pid_pad}}集"
folder_structure = "Season 1"
interval = 60
upper_path = 'C:\Users\001\AppData\Roaming\bili-sync\upper_face'
nfo_time_type = "pubtime"
time_format = "%Y-%m-%d"
cdn_sorting = false

# B站登录凭据信息
# 请从浏览器开发者工具中获取这些值
[credential]
sessdata = "c99d9b5f%2C1764367188%2C0dfb6%2A61CjC7t8i3M2ZpUqfbcGARh1uHMM-HQJcIDZ9J5c3vSX0ylUXvfS_FmEKsC_XhFKw0qAkSVjd0VGVGRTlFdWljZzRWNF9XRV9PVXdCT0I0RWk5Y0w3TUd4LTRIaFhkT1hydUtGMHdRbjVfVXliOG5aZHlPNjU3YzVJdGpaQ2VLY1lROGFiS1JIVW93IIEC"
bili_jct = "1260800f480a8b7c0d4c0f290c72da61"
buvid3 = "F6B872E8-60C0-91FB-4387-A68E65AA51F542133infoc"
dedeuserid = "1591330"
ac_time_value = "39dac70ecf84fc9785349874daaea461"

# 视频质量过滤配置
# 可以设置视频和音频的质量范围
[filter_option]
video_max_quality = "Quality8k"
video_min_quality = "Quality360p"
audio_max_quality = "QualityHiRES"
audio_min_quality = "Quality64k"
codecs = [
    "AVC",
    "HEV",
    "AV1",
]
no_dolby_video = false
no_dolby_audio = false
no_hdr = false
no_hires = false

# 弹幕样式配置
# 用于设置下载弹幕的显示样式
[danmaku_option]
duration = 15.0
font = "黑体"
font_size = 25
width_ratio = 1.2
horizontal_gap = 20.0
lane_size = 32
float_percentage = 0.5
bottom_percentage = 0.3
opacity = 76
bold = true
outline = 0.8
time_offset = 0.0

# 并发下载配置
# video: 同时下载的视频数量
# page: 每个视频同时下载的分页数量
[concurrent_limit]
video = 3
page = 2

[concurrent_limit.rate_limit]
limit = 4
duration = 250

# 多线程下载配置
# enabled: 是否启用多线程下载
# threads: 每个文件的下载线程数
[concurrent_limit.parallel_download]
enabled = true
threads = 16
