[build.env]
passthrough = [
    "BILI_SYNC_DOWNLOAD_ARIA2"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y aria2"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update", 
    "apt-get install -y aria2"
] 