[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y unzip",
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y unzip",
]