[build.env]
passthrough = [
    "BILI_SYNC_DOWNLOAD_ARIA2"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update -y",
    "apt-get install -y --no-install-recommends aria2 unzip curl"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive", 
    "apt-get update -y",
    "apt-get install -y --no-install-recommends aria2 unzip curl"
] 