name: Build and Push Docker Image

on:
  push:
    branches: [ beta, dev ]  # 只在beta和dev分支触发
    tags: [ 'beta*', 'v*-beta*' ]  # 支持beta标签，如 beta1.0.0, v2.7.0-beta1
  # workflow_dispatch:  # 临时禁用手动触发

env:
  REGISTRY: docker.io
  IMAGE_NAME: qq1582185982/bili-sync
  CNB_REGISTRY: docker.cnb.cool
  CNB_IMAGE_NAME: sviplk.com/docker/bili-sync

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to CNB.Cool Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: docker.cnb.cool
        username: cnb
        password: ${{ secrets.CNB_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.IMAGE_NAME }}
          docker.cnb.cool/${{ env.CNB_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ env.IMAGE_NAME }}:beta
          ${{ env.IMAGE_NAME }}:beta-latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Build and push to CNB.Cool Registry
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          docker.cnb.cool/${{ env.CNB_IMAGE_NAME }}:beta
          docker.cnb.cool/${{ env.CNB_IMAGE_NAME }}:beta-latest
          docker.cnb.cool/${{ env.CNB_IMAGE_NAME }}:v2.7.0-beta
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Test Docker image
      if: github.event_name != 'pull_request'
      run: |
        echo "Testing Docker image..."
        docker run --rm ${{ env.IMAGE_NAME }}:beta-latest --help | head -5 || echo "Docker image test completed"
